/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espoch.practicagestiontareas.Vista;

import ec.edu.espoch.practicagestiontareas.tester.TesterVista;

/**
 *
 * @author SO-LAB1-PC20
 */
public class Vista extends javax.swing.JFrame {
    private TesterVista tester;
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.tester = new TesterVista(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textDescripcion = new javax.swing.JTextField();
        lbdTitulo = new javax.swing.JLabel();
        lbdTituloTarea = new javax.swing.JLabel();
        lbdDescripción = new javax.swing.JLabel();
        textTituloTarea = new javax.swing.JTextField();
        rdbCompleta = new javax.swing.JRadioButton();
        rdbIncompleta = new javax.swing.JRadioButton();
        BtnMostrar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        lbdError = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuTareas = new javax.swing.JMenu();
        mItemListar = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDescripcionActionPerformed(evt);
            }
        });

        lbdTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbdTitulo.setText("Gestión de Tareas");

        lbdTituloTarea.setText("Título:");

        lbdDescripción.setText("Descripción:");

        textTituloTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTituloTareaActionPerformed(evt);
            }
        });

        rdbCompleta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdbCompleta.setText("Completa");
        rdbCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCompletaActionPerformed(evt);
            }
        });

        rdbIncompleta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdbIncompleta.setText("Incompleta");

        BtnMostrar.setText("Guardar");
        BtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");

        lbdError.setText("------------------------");

        MenuTareas.setText("Tarea");

        mItemListar.setText("Listar Tareas");
        mItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemListarActionPerformed(evt);
            }
        });
        MenuTareas.add(mItemListar);

        jMenuBar1.add(MenuTareas);

        MenuSalir.setText("Salir");
        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbdTitulo)
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lbdTituloTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textTituloTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbdDescripción)
                                    .addComponent(rdbCompleta)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(BtnMostrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbIncompleta)
                            .addComponent(textDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(BtnLimpiar)))))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lbdError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbdTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdTituloTarea)
                    .addComponent(textTituloTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdDescripción)
                    .addComponent(textDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbCompleta)
                    .addComponent(rdbIncompleta))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMostrar)
                    .addComponent(BtnLimpiar))
                .addGap(41, 41, 41)
                .addComponent(lbdError)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTituloTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTituloTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloTareaActionPerformed

    private void textDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDescripcionActionPerformed

    private void rdbCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCompletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCompletaActionPerformed

    private void mItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemListarActionPerformed
        // TODO add your handling code here:
        ListarTareas objListarTareas = new ListarTareas();
        objListarTareas.setVisible(true);
    }//GEN-LAST:event_mItemListarActionPerformed

    private void BtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarActionPerformed
        // TODO add your handling code here:
        this.tester.prueba();
    }//GEN-LAST:event_BtnMostrarActionPerformed
    
    public String getTitulo(){
     return textTituloTarea.getText();
    }
    
    public String getDescripcion(){
     return textDescripcion.getText();
    }
    
    public boolean getEstado(){
     return rdbCompleta.isSelected();
    }
    
    public void error(String error){
      lbdError.setText(error);
    }
    

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnMostrar;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenu MenuTareas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbdDescripción;
    private javax.swing.JLabel lbdError;
    private javax.swing.JLabel lbdTitulo;
    private javax.swing.JLabel lbdTituloTarea;
    private javax.swing.JMenuItem mItemListar;
    private javax.swing.JRadioButton rdbCompleta;
    private javax.swing.JRadioButton rdbIncompleta;
    private javax.swing.JTextField textDescripcion;
    private javax.swing.JTextField textTituloTarea;
    // End of variables declaration//GEN-END:variables
}
